# INTRODUCTION
The Great Recession caused researchers to shift their focus on the narrative of credit, housing market and financial stability. There has been an increasing interest in the study of the interaction between credit, speculation and house prices [@mian_house_2011; @mian_credit_2018]

[@kishor_forecasting_2020], [@mian_credit_2018], [@guerrieri_housing_2016] and [@davis_housing_2015] have detailed literature reviews on the dynamics between housing market and credit conditions. We will list the four literatures branches that study the dynamics of the credit cycles, housing prices cycles and then the key connection between boom-bust episodes in housing markets and boom-bust episodes in credit markets. There are two approaches to this interaction:(i) The house price cycles generates the credit cycles. (ii) The credit cycles generates the house price cycles.

The first part of the literature focus on how credit cycles are generated. [@kiyotaki_credit_1997] modeled the fluctuation of credit condition due to credit limit and asset prices. The model shows how exogenous shocks can create cyclical fluctuation in credit, asset prices and real output. [@myerson_model_2012] proposed a model of credit cycles generated by moral hazard in dynamic interactions among different generations of financial agents. [@guerrieri_housing_2016] used a catastrophe model for credit, in which multiple equilibria are possible due to adverse selection: as credit increases, the composition of borrowers worsens at this can generate a crash in credit market. [@boissay_booms_2016] studied the topic of endogenous boom and bust in credit market using a dynamic stochastic general equilibrium (DSGE) model, in which moral hazard and asymmetric information may endogenously lead to sudden freezes and crises in the credit market. As for classifying periods of booms and bursts in credit condition, [@alessi_identifying_2018] used a random forest model to identify unsustainable credit growth periods.

The second branch of the literature focus on dynamics of house prices changes. We first look at the generation of momentum in house price changes. Asset prices valuation tend to vary when information about their performance is available. [@thaler_chapter_2005] pointed out that securities with good performance records receive extremely high valuations, and those valuation will return to the mean on average. [@hong_unified_1999] suggested a model with information diffuses gradually across the population, and if agents implement simple univariate strategies, their attempts at arbitrage will lead to overreaction at long horizons. [@capozza_anatomy_2004] analyzed dynamic properties of markets exhibiting serial correlation and mean reversion. These properties allows for prices to overshoot equilibrium (cycles) and diverge permanently from equilibirum. [@glaeser_housing_2008] incorporated housing supply elasticity into the analysis of housing prices momentum and shows that the price run-ups of the 1980s were almost exclusively experienced in cities with more inelastic housing supply. [@head_search_2014] showed that variation in the time it takes to sell houses induces transaction prices to exhibit serially correlated growth. [@glaeser_extrapolative_2017] modeled the  leads house prices expectation approximation to display missing features in rational models: momentum at short run horizon, mean reversion in long run horizon and excess longer-term volatility relative to fundamentals.  [@kishor_time_2015] studied the U.S. housing market by using a combination of Unobserved Component model and GARCH model to study the time-varying importance of permanent and transitory housing components in the U.S. housing prices. [@knoll_no_2017] constructed a house price index for 14 economies in over 140 years. They argue that real house prices have largely followed a "hockey stick" pattern: fairly consistent for a long period of time, then followed by a pronounced increase towards the second half of the century with substantial cross-country variation. Furthermore, they say that most of the price increase can be attributed to the increase in the price of land, and that house prices have risen faster than income in recent decades. [@knoll_return_2016] argued that rise in house prices coincides with a rise the the price-rent ratio, a fundamental that shows intrinsic value of housing. 

We then focus on the housing price booms and busts episodes, by listing a model of irrationality for asset prices. We depart from the rational expectations framework where all agents are perfectly forward-looking and rational, which elimitate the possibility of a bubble in asset prices from starting. In contrast, we assume that households always believe that with some probability there is a "fool" who will buy the asset at a higher price, even though he does not really exists. Two strands of literature have address this challenge. One is called "bubbles", and the other is called "sentiments". 

The "bubbles" models keeps the expected growth rate of bubbles bounded by the growth rate of the economy, thus circumventing the backward induction logic that prevents bubbles from forming at the first place. [@samuelson_exact_1958] was the earliest example of bubbles with  introduction of the overlapping-generations model of money. He pointed out that in an economy that does not provide means of savings that produce a rate of return higher than the growth rate of the economy, then an intrinsically worthless asset (fiat money) can have a nonzero price, hence the term "bubbles". Another stream of the literature that features rational bubbles is the search literatures with fiat money. [@kiyotaki_money_1989] proposed an model of decentralized trade where agents meet randomly and fiat money arise as a general medium of exchange.

The stream of literature of greatest interest to us is the one that has interpreted this transfer scheme of resources as bubble, and has discussed how such bubbles might get introduced by various generations. Some of these paper describe the transfer scheme as stochastic, and might end in any given period with a given probability, generating a crash. Carvalho, Martin and Ventura has a series of papers employing various versions of the overlapping-generation models in which resources are funneled from inefficient savers to efficent entrepreneurs. Particularly, changes in sentiments of investors or market expectations can give rise to credit bubbles. In particular, [@martin_theoretical_2010] used this framework to think about the financial crisis of 2008. In the model, they speculate that there might be some lending friction, where entrepreneurs cannot guarantee repayment. In order to finance the needed capital, they have to issue more paper / worthless "bubble" securities, valued only because the buy hopes that someone else buys them in the future. The issuance of such bubble papers starts another sequence of the intergentartion transfer scheme described above. [@he_housing_2015] focused on housing ability to to facilitate transaction when credit markets are imperfect, housing can collateralizes loans. This liquidity property creates a premium on housing prices. Even when holding fundamentals constant, since liquidity depends on beliefs, self-fulfilling prophecies allow prices to be cyclic, chaotic and stochastic. Also on the topic of beliefs, differences on beliefs of valuation are at the heart of trading in [@scheinkman_overconfidence_2003] : the belief differences create a bubbly component of asset prices. Agents who are overconfident pay prices that exceed their own valuation of future dividens because they believe that in the future they will find a buyer willing to pay even more. This causes a significant bubble component in asset prices even when small differences of beliefs are sufficient to generate a trade. And in equilibrium, bubbles are accelerated by large trading volume and high price volatility. Another paper that allows for bubble to be generated with perfectly rational agents and foresight is [@wright_buyers_2014]. Bubbles here arise in a model of bilateral exchange that involve chains of intermediaries in markets with search frictions and bargaining problem. 

"Sentiments" literature allows agents to believe that bubbles will grow faster than the economy. But it also requires irrational beliefs for a portion of the population in order to disable the backward induction logic that prevents bubbles from forming. Asset prices may be above fundamental value because agents irrationally believe that there is always a "greater fool" who is going be willing to buy at an even higher price. In this summary of the literature, we show a number of variants of this story, where assets a trading above fundamental values due to diverse beliefs between optimists and pessimists, creating a premium above the fundamental value. There are two version of the "sentiments" literature: static and dynamic versions. 

The first example of the static version could be found in [@geanakoplos_liquidity_2001]. The paper stated that the possibility of default limits available liquidity. When the probability of default increases, a liquidity crisis may ensue, causing a crash in asset prices. [@simsek_belief_2013] suggested that belief disagreements are major contributing factor to the recent subprime mortgage crisis. Since pessimists do not value the collateral as much as optimists do, pessimists are reluctant to lend, which gives an endogenous constraint on optimists' ability to borrow and this influence asset prices. The second variant of the story is "dynamic version" as found in [@harrison_speculative_1978] and [@scheinkman_overconfidence_2003]. In these papers, agents pay prices that exceed their own valuation of future dividends because they believe that in the future they will find a buyer willing to pay even more. However, in [@scheinkman_overconfidence_2003], agents do understand that bubble will not grow faster than the economy, on average. [@glaeser_housing_2008] claimed that rational bubbles can exist, if there is no new construction. The price run-ups of the 1980s were almost exclusively experienced in cities where housing supply is more inelastic. The paper rule out bubbles with elastic housing supply, and then proceed to use a model of irrational, exuberant buyers to study housing bubbles, relating the length of frequency of bubbles to the elasticity of housing supply. The dynamic sentiments literature focus on either of the extreme end of the population, the pessimists and optimists. The optimists by construction, must be the "greatest fool". Where the "greatest fool" must be someone willing to pay for something that is intrinsically worthless, without ever being able to sell to someone at an even higher price.  Alternatively, an additional idea would be that optimistic buyers are not yet the greatest fools themselves, but simpy betting on even greater fools existing out there. There may be quite foolish people out there with overly strong optimism of being able to sell to such "greatest fools". At the end, these models require substantial irrationality. However, the key here is that this suspected strong irrationality at the upper end of the distribution trickle down the the price dynamic among the less fooling or even perfectly rational part of the population. 
The model that share many of the above mention elements is [@golosov_decentralized_2014]. Assets are traded in a decentralized market with agents having different information regarding the fundamental value of the asset. Overtime, uninformed agents can infer information from others by making small offers, as long as there are potential gains from trade in the economy. Every one understands that the asset have a bubbly component. The differences arise in beliefs regarding the optimism of others. 
 A benchmark example for a dynamic model focusing on heterogeneous beliefs and changing sentiments, the "disease" bubble, is used in [@burnside_understanding_2016]. An initially pessimistic population may gradually become "infected" to be optimistic and believe the worthless bubble component actually has some intrinsic value. It is difficult for agents to find observable fundamentals that are useful for predicting whether a boom will bust or not. Agents have heterogeneous expectations about long-run fundamentals but change their views because of "social dynamics". Asset prices might rise during the periods of changing sentiment. However, "truth" may be revealed at some probability every period, and clarify that bubble component is worthless indeed, leading to a bust.  Another related paper is [@bordalo_diagnostic_2018], where credit cycles arise from "diagnostic expectations", from the assumption that when they form expectations agents overweight future outcomes that seems more likely in light of recent data. This overweighing due to updating data can cause credit spread to be subject to excess volatility and over-reaction to news. 
 
The third branch of literature is the one that studies the (i) hypothesis that house price cycles generates the credit cycles. The dynamics of houses price on household credit can be viewed through the lens of the borrower balance sheet. [@bernanke_agency_1989] developed a  neoclassical model of the business cycle in which the condition of borrowers' balance sheets is a source of output dynamics. The mechanism is that higher borrower net worth reduces the agency costs of financing real capital investments. The financial acceleration effects implies that stronger balance sheets due to higher asset prices will lead to lower cost of borrowing to invest. Which suggests that a boom in housing prices will lead to a boom in credit. [@kiyotaki_credit_1997] further incorporated this positive feedback through asset prices, and the associated intertemporal multiplier process that affect borrowing capacity and output into their paper. An increase in home equity due to increase in house prices will allow borrower to borrow more to finance either personal consumption or more speculation housing investment. [@mian_credit_2018]  showed that the crash in the housing market and following credit crunch showed the importance of housing prices for household balance sheet as well as banking sector balance sheet.

In the final branch of literature we will list papers that study the (ii) hypothesis that credit cycles generates house price cycles. [@agnello_booms_2011],  [@agnello_economic_2018] examined different variables that are likely to create a bubble in housing markets. We will look at the effects of credit constraint condition, financial innovation and credit expansion on house prices. First is the effect of credit constraint on house prices. [@stein_prices_1995] is the first paper to explore the effects of down-payment requirements on house price volatility. The paper highlighted the self-reinforcing effect that runs from house prices to down payments and housing demand, back to house prices. If house prices decline, the value of households' collateral declines, depressing houseing demand and hence pushing house prices further down. This multiplier effect can generate multiple equilibiria and account for the house price boom-bust episodes. The self-reinforcing effect has the same spirit of the transmission mechanism put forth by [@kiyotaki_credit_1997]. In a recent related paper, [@ortalo-magne_housing_2006] showed that income volatility of young households or relaxation of their credit constraints can explain excess volatility of house prices through identifying a powerful driver of the housing market: the ability of young households to afford the down payment on a starter home. 

The second part of this literature branch is the effect of financial innovation, or financial liberalization on house prices.  [@kermani_cheap_2012] proposed a model to emphasize the importance of financial liberalization and its reversal to explain the housing boom and bust. [@he_housing_2015] also proposed a model where housing collateralizes loans and house price boom and bust can be generated by financial innovation because the liquidity premium on housing is non-monotone in the loan-to-equity ratio. [@huo_financial_2016] had a model with heterogenous households, housing and credit constraints, and also show that financial shocks can generate large drops in housing prices. [@favilukis_international_2012] studied the impact of systemic changes in housing finance: changes in housing collateral requirements and the change in borrowing costs (the spread of mortgage rates over risk-free security) on how these factors affect risk premiums in housing markets, and how those risk premiums in turn affect home prices.[@favilukis_macroeconomic_2017] developed a quantitative general equilibirum model with housing and collateral constraints to explore what drives fluctuations in house prices to rent ratio. They propose that a relaxation of financing constraints leads to a large boom in house prices. And the boom in house prices is entirely the result of a decline in the housing risk premium. [@mian_credit_2018] showed that speculation is a critical channel through which credit supply expansion affects the housing cycle. 

In the last part of this literature branch, we list studies on effects of credit expansion on house prices. [@justiniano_credit_2019] argued that loosening of the collateral requirements alone cannot explain the recent housing boom in the US, but there must have been an expansion in the credit supply. The authors argued that house prices rose from 2000 to 2007 without an expansion of leverage. The cause that lead to the housing boom before recession was because of an increase in credit supply or available funds rather than an increase in leverage. The rates of mortgages to real estate remained constant. This contradict with the popular view that attributes the housing boom to looser borrowing constraints associated with lower collateral requirements, which would shift the demand for credit. In short, the increase in supply of credit was the cause of housing boom. Beyond 2007, the paper argues that there was an increase in collateralizing houses relative to available funds, or that available funds for lending decreased, leading to a rise in mortgage rates and a collapse of house prices. More interestingly, Jorda, Schularick and Taylor have studied the interplay between credit cycles, house price cycles and economic performance in a series of papers. [@schularick_credit_2012] created a new data sets for 14 developed countries over 140 years and showed how credit growth is a powerful predictor of financial crises. [@jorda_great_2016] claimed that mortgage lending booms were loosely related to financial crisis before WWII, but have become a more important predictor of financial fragility after. The share of mortgages on banks' balance sheets doubled in the later half of twentieth century, driven by a rise of mortgage lending to households. Household debt to asset ratios have risen substantially in many countries in the study. Financial stability risks have been linked to real estate lending booms.[@jorda_betting_2015] claim that there has been an increase in the mentality of "bets on the house" in the past century. Mortgage credit has risen dramatically as a share of banks' balance sheets from about one third at the beginning of the last century, to about two thirds nowadays. They use a novel IV local projection methods to demonstrate that loose monetary conditions lead to booms in real estate and house prices' bubbles. These in turn leads to higher risk of financial crises. Mortgage booms and house price bubbles have been closely associated with a higher likelihood of a financial crisis.[@jorda_macrofinancial_2017] claimed that a century-long and stable ratio of credit to GDP gave way to rapid financialization and surging leverage in the last forty years. This coincide with a shifts in foundational macroeconomic relationships. More financialized economies exhibit more tail risk, as well as tighter real-real and real-financial correlations, including of course the credit and real estate correlation. The paper also show that both real house prices and mortgages in 17 sample countries display a "hockey stick" in their patterns. Meaning they both stay stable for a long period of time before ticking up drastically at the end of the sample. It can be shown that house price growth and mortgage growth generally co-move. [@favara_credit_2015] showed an expansion in mortgage credit has significant effects on house prices using a spatial IV-strategy with the US branching deregulation between 1994 and 2005 as an instrument for credit. The treated banks credit expansion lead to increases in housing demand. [@di_maggio_credit-induced_2017] showed that a credit expansion can generate a boom and bust in house prices and real activity. The paper use the exploitation of the same federal deregulation in preemption of local laws against predatory lending in 2004 to gauge the effect of the supply of credit on the real economy.

However, the debate on whether house prices have been the main driving source of the credit cycle, or financial conditions (credit) are the main driving force of house price cycle is still open. In this paper, I hope to bring a dynamic model in order to be able explain the relationship between the two series. 

The findings in the literature motivate further examination in the structure of the relation between household credit and house prices. The novel contribution of this study is to develop a model to jointly examine the two variables of interest: household credit and house prices and their interaction. This study will look into the interaction between short term transitory and long term permanent components of household credit and house prices. The methodology that I use in this paper to extract transitory and permanent information from non-stationary time series is a decomposition method called Unobserved Components model pioneered by [@beveridge_new_1981]. The implementation details of the methodology is inspired by [@morley_slow_2007] and [@huang_rise_2019].  This method allows the permanent component to be shown as a random walk and the transitory component to be a stationary process with mean zero. The stationary transitory component configuration is important to infer meaningful structural linkage between the two variables of interest: household credit and house prices; as non-stationary transitory components do not offer meaningful inferences. This brings up the paper's second novel contribution to the literature. By explicitly configuring cross correlation coefficients on the cyclical components of the two variables, we will be able to examine the preditive ability of the cycles. This would produce a much desired inference for macroprudential policy implication to stabilize the macroeconomy.

We find interesting and meaningful results from the estimated multivariate correlated unobserved component model. The maximum-likelihood estimates of our correlated multivariate UC model suggest that there is a strong positive correlation between the transitory shock to household credit and the transitory shock to the house prices index. This suggests that a temporary increase in household credit is associated with an increase in house prices above its long-run level. These results support the narrative evidence on the strong relationship between household credit and house prices. More importantly, we also find evidence that lags of household credit cycle has predictive ability in forecasting the magnitude of house prices gap above its long-run level by examining the cross correlation coefficient on the cyclical components. We also find that the trend-cycle decomposition of the two variables of interest captures the recent boom and bust behavior and compares favorably to a univariate trend-cycle decomposition benchmark.

The plan of the paper is as followed, in the section 2 we will introduce the summary of data and their description. In section 3, we will lay out the details of the decomposition methodology using unobserved component model with vector auto-regression (VAR). In section 4, we will go over results of the model regression and our interpretation. In section 5, we will test the robustness of the model by comparing the results against some traditional method of analyzing time series data. And lastly, in section 6, we will give our conclusion remark for the model.
