
# Conclusion

Our study is based on the idea that excessive credit growth measured by the total credit to GDP deviations could be used as an early warning indicator for future systemic financial crises. We build a novel framework to select relevant credit gap decomposition filters, average their combinations, and create a crisis-weighted credit gap that inherits the combined features of the selected filters. We also proposed a novel performance metric for early warning indicator psAUC with a specific constraint that has appealing policy implication properties. 

Our findings in this paper provide robust evidence to show the superior predictive performance of our proposed weighted credit gap over other univariate early warning indicator models that use individual credit gap filters. The novel proposed metric psAUC also showed that it has appealing properties for policy maker. It simplifies the steps to search for a decomposition filter with minimized loss function in the range of credit gap thresholds with Type II error rates smaller than 1/3. Therefore, the weighted gap and novel metric can be regarded as useful additional reference points for policy implications.

\clearpage


<!--(References for closing: one of the 6 reference papers)
We have created a system ... (Alessi 2017)
summarize opening assumptions, findings, contributions
Policy implication, reference
Future improvement-->
